<a href="https://colab.research.google.com/github/Chinki021/pandas/blob/main/5)GroupByAggregation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.DataFrame({
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)

})
data

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [4]:
# Group by Category and calculate the sum of Sales
c=data.groupby('Category')['Sales'].sum()
c

Category
A    570
B    930
Name: Sales, dtype: int64

In [5]:
# Group by Store and calculate the sum of Sales
c=data.groupby('Store')['Sales'].sum()
c

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [8]:
# Group by multiple columns
# Group by Category and Store
c=data.groupby(['Category','Store'])['Sales'].sum()
c

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

In [13]:
#numeric_only
#numeric_only is used when a dataframe contains both numeric and non-numeric columns, but you want an operation like mean(),sum()etc . but in modern versions of pandas , this usually does not need bcz non-numeric columns are automatically ignored.

In [15]:
data.groupby('Sales').count()
# difference b/w count() and size()
# count() = counts non null values column by column
# size()= counts total rows,including rows with missing values

       Category  Store  Quantity  Date
Sales
100           1      1         1     1
120           1      1         1     1
150           1      1         1     1
180           1      1         1     1
200           2      2         2     2
250           1      1         1     1
300           1      1         1     1

Aggregation

In [9]:
data['Sales'].mean()
#mean,median,mode,min,max,count,std

np.float64(187.5)

In [11]:
data['Sales'].agg(['mean','min','max'])

mean    187.5
min     100.0
max     300.0
Name: Sales, dtype: float64