<a href="https://colab.research.google.com/github/Chinki021/pandas/blob/main/7)Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

dataframe basic operations

In [2]:
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})

In [3]:
df1.shape

(5, 3)

In [4]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [5]:
df1.columns

Index(['A', 'B', 'C'], dtype='object')

In [6]:
#addition
df1['A']+df1['B']    #same goes with substraction, multiplication, division

0    11
1    22
2    33
3    44
4    55
dtype: int64

In [8]:
#creating a new column
df1['total']=df1['A']-df1['B']
print(df1['total'])

0    -9
1   -18
2   -27
3   -36
4   -45
Name: total, dtype: int64

In [10]:
 #comparision opertor
 df1['A']>15

0    False
1    False
2    False
3    False
4    False
Name: A, dtype: bool

In [12]:
#filtering

students = pd.DataFrame({
    "Name":["A","B","C","D"],
    "Marks":[70,85,90,60]
})

In [14]:
students[students['Marks']>70]

  Name  Marks
1    B     85
2    C     90

In [15]:
#multiple conditions
students[(students['Marks']>80) & (students['Marks']<90)]

  Name  Marks
1    B     85

In [18]:
#assending sorting
students.sort_values('Marks',ascending=True)

  Name  Marks
3    D     60
0    A     70
1    B     85
2    C     90

In [19]:
#descending sorting
students.sort_values('Marks', ascending=False)

  Name  Marks
2    C     90
1    B     85
0    A     70
3    D     60

In [20]:
#value counts
df = pd.DataFrame({
    "Department":["IT","HR","IT","Finance","HR"]
})

In [22]:
df['Department'].value_counts()

Department
IT         2
HR         2
Finance    1
Name: count, dtype: int64

In [23]:
df["Department"].unique()

array(['IT', 'HR', 'Finance'], dtype=object)

In [24]:
df.duplicated()

0    False
1    False
2     True
3    False
4     True
dtype: bool

In [27]:
df=pd.DataFrame({
    'Name':['Chinki','Lali','Peeli','Neelii'],
    'Salary':[1000,30000,6000,345000]
  })
df

     Name  Salary
0  Chinki    1000
1    Lali   30000
2   Peeli    6000
3  Neelii  345000

In [29]:
#now increase salary by 10%
df['Salary']=df['Salary'].apply(lambda x:x*1.1)
df['Salary']

0      1210.0
1     36300.0
2      7260.0
3    417450.0
Name: Salary, dtype: float64